# Generated by Django 3.0.7 on 2020-07-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_phone_number', models.CharField(max_length=15)),
                ('visitor_mail', models.EmailField(max_length=254)),
                ('reason', models.CharField(max_length=100)),
                ('visitor_address', models.CharField(max_length=500)),
                ('contact_person', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
