# Generated by Django 3.0.7 on 2020-07-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_auto_20200702_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='photo',
        ),
    ]
